name: Check React With Sonar

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: 'Token of the Platform Builders server'
        required: true
      SONAR_HOST_URL:
        description: 'Url of the Platform Builders server'
        required: true
      PACKAGES_NPMRC:
        description: 'Token of the Builders Github Packages'
        required: true

jobs:
  sonar:
    uses: ./.github/workflows/sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  check:
    name: Check React
    uses: ./.github/workflows/check-react-shared.yml
    needs: sonar
    secrets:
      PACKAGES_NPMRC: ${{ env.PACKAGES_NPMRC }}
    with:
      IS_REQUIRED_SET_PACKAGES_NPMRC: true
